// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `node scripts/generate_audio.js` to regenerate with API key.

export const audioMap = {
  "Hi! I'm Tally. Ready to explore picture graphs and become a data detective? Let's begin our journey!": "/assets/audio/audio_hi_im_tally_ready_to_explore_picture_graphs_and_be_0.mp3",
  "The Big Fun Fair Mystery!": "/assets/audio/audio_the_big_fun_fair_mystery_1.mp3",
  "If Sophie has 4 apple stickers on her poster with a key of 1 apple = 2 votes, why does that mean 8 votes instead of 4?": "/assets/audio/audio_if_sophie_has_4_apple_stickers_on_her_poster_with__2.mp3",
  "Let's investigate how picture graphs and keys work!": "/assets/audio/audio_lets_investigate_how_picture_graphs_and_keys_work_3.mp3",
  "Sophie and Max set up a Favourite Fruit voting booth at the school fun fair. Every classmate who walks past gets to stick one fruit sticker on the poster for their favourite fruit. By lunchtime, the poster is covered in little fruit pictures!": "/assets/audio/audio_sophie_and_max_set_up_a_favourite_fruit_voting_boo_4.mp3",
  "Ms. Emma helps the class line up the stickers into neat rows — one row per fruit. This is called a picture graph! She explains that every picture graph needs a key that tells us how much one picture is worth. Today's key is: 1 apple equals 2 votes.": "/assets/audio/audio_ms_emma_helps_the_class_line_up_the_stickers_into__5.mp3",
  "Henry counts the apple row — there are 4 apple pictures — and shouts, '4 students chose apples!' Sophie gently stops him. 'Wait, Henry — check the key first! Each picture is worth 2 votes, so 4 pictures means 4 times 2 equals 8 votes, not 4!'": "/assets/audio/audio_henry_counts_the_apple_row_there_are_4_apple_pictu_6.mp3",
  "The finished graph shows: Apples 8 votes, Bananas 6 votes, Grapes 4 votes, Oranges 2 votes. The class practises together — which fruit got the most votes? Which got the fewest? How many votes were there in all? Eight plus six plus four plus two equals twenty votes altogether!": "/assets/audio/audio_the_finished_graph_shows_apples_8_votes_bananas_6__7.mp3",
  "Apples won with 8 votes — the most of any fruit! So the fun fair orders apple juice for the snack stand. Sophie cheers: she can now read the key, count a category, compare fruits, and find the total. She is officially a Picture Graph Pro! Let's practise together!": "/assets/audio/audio_apples_won_with_8_votes_the_most_of_any_fruit_so_t_8.mp3",
  "Station A: Key Scaler! Change the scale value to see how the number of picture symbols changes while the real vote count stays the same!": "/assets/audio/audio_station_a_key_scaler_change_the_scale_value_to_see_9.mp3",
  "Station B: Graph Builder! Look at the survey data table and add picture symbols to each row until your picture graph is complete!": "/assets/audio/audio_station_b_graph_builder_look_at_the_survey_data_ta_10.mp3",
  "Station C: Scale Detective! Use the clue to crack the secret key and unlock the hidden votes!": "/assets/audio/audio_station_c_scale_detective_use_the_clue_to_crack_th_11.mp3",
  "Station D: Spot the Error! One of the pictograph rows has a counting mistake. Tap the error and fix it!": "/assets/audio/audio_station_d_spot_the_error_one_of_the_pictograph_row_12.mp3",
  "Amazing! You solved the picture graph puzzle!": "/assets/audio/audio_amazing_you_solved_the_picture_graph_puzzle_13.mp3",
  "Not quite! Check the key and try again.": "/assets/audio/audio_not_quite_check_the_key_and_try_again_14.mp3",
  "Amazing! You read the graph perfectly!": "/assets/audio/audio_amazing_you_read_the_graph_perfectly_15.mp3",
  "Brilliant! That is exactly right!": "/assets/audio/audio_brilliant_that_is_exactly_right_16.mp3",
  "Superb! Great data detective work!": "/assets/audio/audio_superb_great_data_detective_work_17.mp3",
  "Excellent! Picture graph mastery at work!": "/assets/audio/audio_excellent_picture_graph_mastery_at_work_18.mp3",
  "Perfect! You checked the key carefully!": "/assets/audio/audio_perfect_you_checked_the_key_carefully_19.mp3",
  "Fantastic streak! Keep on rolling!": "/assets/audio/audio_fantastic_streak_keep_on_rolling_20.mp3",
  "Let's check the key and multiply again!": "/assets/audio/audio_lets_check_the_key_and_multiply_again_21.mp3",
  "Hint: Look at the key at the bottom of the graph to see what one picture equals.": "/assets/audio/audio_hint_look_at_the_key_at_the_bottom_of_the_graph_to_22.mp3",
  "Hint: Multiply the number of pictures in the row by the key value.": "/assets/audio/audio_hint_multiply_the_number_of_pictures_in_the_row_by_23.mp3",
  "Excellent work! You completed this district!": "/assets/audio/audio_excellent_work_you_completed_this_district_24.mp3",
  "The Boss Battle begins! Answer the questions correctly with your 3 lives to defeat the boss!": "/assets/audio/audio_the_boss_battle_begins_answer_the_questions_correc_25.mp3",
  "Victory! You defeated the boss and claimed your Picto Master reward!": "/assets/audio/audio_victory_you_defeated_the_boss_and_claimed_your_pic_26.mp3",
  "Take a moment to reflect on your learning and check your pictograph scorecard!": "/assets/audio/audio_take_a_moment_to_reflect_on_your_learning_and_chec_27.mp3",
  "Congratulations! You have mastered reading picture graphs, scales, keys, and data totals! You are an official Picture Graph Pro!": "/assets/audio/audio_congratulations_you_have_mastered_reading_picture__28.mp3",
};

export default audioMap;
